baseURL = "https://dispersion-fi.github.io/docs/"
languageCode = "en-us"
title = "Dispersion"
theme = "book"

[params]
    BookTheme = 'dark'
    BookLogo = 'img/logo.jpg'
    BookServiceWorker = true